/**
 * Communication Prompt Generators for InfoFlip-AI Module 4
 * 
 * SIH 2026 - Problem Statement ID 26154
 * Module 4: Social & Communication Generator
 * 
 * Formulates strict anti-hallucination system and user prompts
 * grounded entirely in Module 1 source, Module 2 analysis, and Module 3 transformation outputs.
 */

import { getCommunicationChannelById } from './communicationChannelRegistry.js';
import { isEmergencyContent } from './linkedInPostBuilder.js';

export function buildCommunicationSystemPrompt() {
  return `You are the Social & Communication Generator (Module 4) of InfoFlip-AI (SIH 2026 Problem Statement ID 26154).
Your mission is to specialize structured content generated by Module 3 into high-impact, communication-ready assets across designated channels.

STRICT ANTI-HALLUCINATION & QUALITY RULES:
1. Every factual statement, number, statistic, date, name, location, and instruction MUST originate directly from:
   - Module 1 source text
   - Module 2 semantic analysis (keyFacts, entities, importantNumbers, importantDates)
   - Module 3 transformation outputs
2. NEVER invent:
   - Weather alerts, alert levels (e.g. Red/Orange/Yellow), or affected zones not mentioned in source
   - Statistics, percentages, wind speeds, rainfall numbers, or metrics
   - Dates, deadlines, forecast periods, or schedules
   - Names of people, organizations, or official authorities
   - Emergency deployments (e.g. NDRF, SDRF) or official statements not in source
   - Emergency contact numbers or helplines (use helpline like 112 only if present in source, otherwise advise consulting official channels)
   - Unverified citations, claims, or URLs
   - NEVER strengthen safety directives beyond what the source explicitly states (e.g. do NOT turn "avoid unnecessary travel" into "stay indoors" or mandatory evacuation orders)
   - NEVER add phrases like "officially confirmed", "verified data", or "real-time official feed" without evidence
3. LINKEDIN POST RULES:
   - Single clear relevant title/hook. NEVER use repetitive redundant headings (e.g. do NOT follow "Key Development" with "Strategic Update" or duplicate title lines).
   - For emergency, disaster-response, weather-alert, and public-safety content:
     * NEVER include generic engagement questions such as "What are your thoughts on this?", "How is your organization addressing this?", or "Join the conversation below".
     * Prioritize clear safety instructions, essential directives, and concise formatting over promotional language.
     * Include 3-5 relevant, readable hashtags (e.g. #WeatherAlert, #PublicSafety, #DisasterPreparedness). Avoid extremely long hashtags.
   - For standard professional topics: use professional framing, concise bullets, and relevant professional call-to-action.
4. Clearly distinguish source-stated facts from communication phrasing.
5. Adapt tone, conciseness, and format to each platform's natural conventions while strictly preserving factual grounding.
6. Support accurate English, Hindi, and Marathi outputs based on requested language.
7. Provide source traceability references for key facts used in each channel.

You MUST respond strictly with valid JSON conforming to the following structure:
{
  "outputs": [
    {
      "channelId": "linkedin" | "twitter" | "whatsapp" | "email" | "sms" | "announcement" | "cta" | "hashtags",
      "title": "String title for the communication card",
      "content": "Full formatted text string ready to copy/share directly",
      "structuredData": {
        // Optional platform-specific structured fields (e.g. subject, preview, posts array for twitter thread, ctaVariants, tags array)
      },
      "sourceTraceability": [
        { "fact": "Direct fact quoted or referenced from source", "sourceId": "id" }
      ]
    }
  ]
}`;
}

export function buildCommunicationUserPrompt(request) {
  const {
    sourceId = 'src-1',
    sourceContent = {},
    analysis = {},
    transformationOutputs = [],
    config = {},
    requestedChannels = []
  } = request;

  const rawText = sourceContent.extractedText || sourceContent.rawText || '';

  // Summarize key facts from Module 2
  const factsList = Array.isArray(analysis.keyFacts)
    ? analysis.keyFacts.map((f, i) => `${i + 1}. ${typeof f === 'string' ? f : f.fact}`).join('\n')
    : 'None detected.';

  // Summarize numbers & dates
  const datesList = Array.isArray(analysis.importantDates)
    ? analysis.importantDates.map(d => `${d.date} (${d.context || ''})`).join(', ')
    : 'None';
  const numbersList = Array.isArray(analysis.importantNumbers)
    ? analysis.importantNumbers.map(n => `${n.value} (${n.label || n.context || ''})`).join(', ')
    : 'None';

  // Summarize Module 3 transformation outputs if available
  let mod3Summary = '';
  if (Array.isArray(transformationOutputs) && transformationOutputs.length > 0) {
    mod3Summary = transformationOutputs.map(out => {
      const format = out.format || out.channelId || 'format';
      const contentStr = typeof out.content === 'string' 
        ? out.content.slice(0, 300) 
        : JSON.stringify(out.content).slice(0, 300);
      return `[Module 3 Output - ${format}]:\n${contentStr}...`;
    }).join('\n\n');
  }

  // Format channel-specific guidelines
  const channelInstructions = requestedChannels.map(channelId => {
    const channelDef = getCommunicationChannelById(channelId);
    if (!channelDef) return `- ${channelId}: Generate standard communication asset.`;
    return `### Channel: ${channelDef.name} (${channelDef.id})
Max Characters: ${channelDef.maxCharacters}
Instructions:
${channelDef.promptInstructions}`;
  }).join('\n\n');

  const isEmerg = isEmergencyContent(request);
  const emergencySection = isEmerg ? `
==============================
⚠️ EMERGENCY & PUBLIC SAFETY DIRECTIVE
==============================
- This request is classified as URGENT PUBLIC SAFETY / DISASTER RESPONSE.
- For LinkedIn:
  * Prioritize clear safety instructions, essential actions, and concise scannable bullet points over promotional language.
  * NEVER include generic engagement questions like "What are your thoughts on this?". Use official directives / helplines.
  * Single clear title. DO NOT output repetitive headings (e.g. no "Key Development" followed by "Strategic Update").
  * Use 3-5 readable hashtags (e.g. #WeatherAlert, #PublicSafety, #DisasterPreparedness). Avoid extremely long concatenated hashtags.
- Ground all guidance strictly in source facts. DO NOT invent alert tiers, unstated helplines, or imaginary casualty figures.
` : '';

  return `Please generate communication-ready assets for the following requested channels:
Requested Channels: ${requestedChannels.join(', ')}
${emergencySection}
==============================
CONFIGURATION & AUDIENCE
==============================
Target Audience: ${config.targetAudience || 'General Public'}
Tone: ${config.tone || 'Informative'}
Language: ${config.language || 'English'}
Detail Level: ${config.detailLevel || 'Balanced'}
Objective: ${config.objective || 'Inform'}
Content Style: ${config.style || 'Structured'}

==============================
GROUND TRUTH & FACTS
==============================
Source ID: ${sourceId}
Main Topic: ${analysis.overview?.mainTopic || 'Not specified'}
Source Text (Ground Truth):
${rawText}

Grounded Key Facts from Source (Module 2):
${factsList}

Important Dates: ${datesList}
Important Numbers / Statistics: ${numbersList}
Urgency Level: ${analysis.urgency?.level || 'Standard'}

==============================
MODULE 3 STRUCTURED CONTENT (Base reference)
==============================
${mod3Summary || 'Direct adaptation from source and analysis.'}

==============================
CHANNEL-SPECIFIC REQUIREMENTS
==============================
${channelInstructions}

Generate the outputs array in JSON format. Ground every factual claim in the provided source/analysis facts.`;
}
