/**
 * Communication Prompt Generators for InfoFlip-AI Module 4
 * 
 * SIH 2026 - Problem Statement ID 26154
 * Module 4: Social & Communication Generator
 * 
 * Formulates strict anti-hallucination system and user prompts
 * grounded entirely in Module 1 source, Module 2 analysis, and Module 3 transformation outputs.
 */

import { getCommunicationChannelById } from './communicationChannelRegistry.js';

export function buildCommunicationSystemPrompt() {
  return `You are the Social & Communication Generator (Module 4) of InfoFlip-AI (SIH 2026 Problem Statement ID 26154).
Your mission is to specialize structured content generated by Module 3 into high-impact, communication-ready assets across designated channels.

STRICT ANTI-HALLUCINATION RULES:
1. Every factual statement, number, statistic, date, name, location, and instruction MUST originate directly from:
   - Module 1 source text
   - Module 2 semantic analysis (keyFacts, entities, importantNumbers, importantDates)
   - Module 3 transformation outputs
2. NEVER invent:
   - Statistics, percentages, or metrics
   - Dates, deadlines, or schedules
   - Names of people, organizations, or authorities
   - Emergency contact numbers or helplines
   - Unverified citations, claims, or URLs
3. Clearly distinguish source-stated facts from communication phrasing.
4. Adapt tone, conciseness, and format to each platform's natural conventions while strictly preserving factual grounding.
5. Provide source traceability references for key facts used in each channel.

You MUST respond strictly with valid JSON conforming to the following structure:
{
  "outputs": [
    {
      "channelId": "linkedin" | "twitter" | "whatsapp" | "email" | "sms" | "announcement" | "cta" | "hashtags",
      "title": "String title for the communication card",
      "content": "Full formatted text string ready to copy/share directly",
      "structuredData": {
        // Optional platform-specific structured fields (e.g. subject, preview, posts array for twitter thread, ctaVariants, tags array)
      },
      "sourceTraceability": [
        { "fact": "Direct fact quoted or referenced from source", "sourceId": "id" }
      ]
    }
  ]
}`;
}

export function buildCommunicationUserPrompt(request) {
  const {
    sourceId = 'src-1',
    sourceContent = {},
    analysis = {},
    transformationOutputs = [],
    config = {},
    requestedChannels = []
  } = request;

  const rawText = sourceContent.extractedText || sourceContent.rawText || '';

  // Summarize key facts from Module 2
  const factsList = Array.isArray(analysis.keyFacts)
    ? analysis.keyFacts.map((f, i) => `${i + 1}. ${typeof f === 'string' ? f : f.fact}`).join('\n')
    : 'None detected.';

  // Summarize numbers & dates
  const datesList = Array.isArray(analysis.importantDates)
    ? analysis.importantDates.map(d => `${d.date} (${d.context || ''})`).join(', ')
    : 'None';
  const numbersList = Array.isArray(analysis.importantNumbers)
    ? analysis.importantNumbers.map(n => `${n.value} (${n.label || n.context || ''})`).join(', ')
    : 'None';

  // Summarize Module 3 transformation outputs if available
  let mod3Summary = '';
  if (Array.isArray(transformationOutputs) && transformationOutputs.length > 0) {
    mod3Summary = transformationOutputs.map(out => {
      const format = out.format || out.channelId || 'format';
      const contentStr = typeof out.content === 'string' 
        ? out.content.slice(0, 300) 
        : JSON.stringify(out.content).slice(0, 300);
      return `[Module 3 Output - ${format}]:\n${contentStr}...`;
    }).join('\n\n');
  }

  // Format channel-specific guidelines
  const channelInstructions = requestedChannels.map(channelId => {
    const channelDef = getCommunicationChannelById(channelId);
    if (!channelDef) return `- ${channelId}: Generate standard communication asset.`;
    return `### Channel: ${channelDef.name} (${channelDef.id})
Max Characters: ${channelDef.maxCharacters}
Instructions:
${channelDef.promptInstructions}`;
  }).join('\n\n');

  return `Please generate communication-ready assets for the following requested channels:
Requested Channels: ${requestedChannels.join(', ')}

==============================
CONFIGURATION & AUDIENCE
==============================
Target Audience: ${config.targetAudience || 'General Public'}
Tone: ${config.tone || 'Informative'}
Language: ${config.language || 'English'}
Detail Level: ${config.detailLevel || 'Balanced'}
Objective: ${config.objective || 'Inform'}
Content Style: ${config.style || 'Structured'}

==============================
GROUND TRUTH & FACTS
==============================
Source ID: ${sourceId}
Main Topic: ${analysis.overview?.mainTopic || 'Not specified'}
Source Text (Ground Truth):
${rawText}

Verified Key Facts (Module 2):
${factsList}

Important Dates: ${datesList}
Important Numbers / Statistics: ${numbersList}
Urgency Level: ${analysis.urgency?.level || 'Standard'}

==============================
MODULE 3 STRUCTURED CONTENT (Base reference)
==============================
${mod3Summary || 'Direct adaptation from source and analysis.'}

==============================
CHANNEL-SPECIFIC REQUIREMENTS
==============================
${channelInstructions}

Generate the outputs array in JSON format. Ground every factual claim in the provided source/analysis facts.`;
}
