import React, { useState } from 'react';
import {
  Sparkles,
  Cpu,
  AlertTriangle,
  AlertCircle,
  UserCheck,
  CheckCircle2,
  Info
} from 'lucide-react';
import { CONTENT_STATUS_FLAGS } from '../../types/contentConfidence.js';

const BADGE_CONFIG = {
  [CONTENT_STATUS_FLAGS.AI_GENERATED]: {
    label: 'AI-generated',
    icon: Sparkles,
    badgeClass: 'bg-surface-selected text-text-primary border-border',
    dotClass: 'bg-primary dark:bg-accent',
    description: 'Generated by an AI provider (e.g. Gemini 3.8 Flash). Content requires fact-checking and does not guarantee factual correctness.'
  },
  [CONTENT_STATUS_FLAGS.RULE_BASED_FALLBACK]: {
    label: 'Rule-based fallback',
    icon: Cpu,
    badgeClass: 'bg-warning-subtle text-warning border-warning/30',
    dotClass: 'bg-warning',
    description: 'Generated using deterministic algorithmic fallback rules when AI model was unavailable or rate-limited.'
  },
  [CONTENT_STATUS_FLAGS.VERIFICATION_REQUIRED]: {
    label: 'Verification required',
    icon: AlertTriangle,
    badgeClass: 'bg-warning-subtle text-warning border-warning/30',
    dotClass: 'bg-warning',
    description: 'High-risk or time-sensitive factual claim that has not been independently verified against official authorities.'
  },
  [CONTENT_STATUS_FLAGS.POTENTIAL_ISSUE_DETECTED]: {
    label: 'Potential issue detected',
    icon: AlertCircle,
    badgeClass: 'bg-error-subtle text-error border-error/30',
    dotClass: 'bg-error',
    description: 'A possible factual inconsistency, unsupported claim, or quality assurance warning was flagged.'
  },
  [CONTENT_STATUS_FLAGS.HUMAN_REVIEWED]: {
    label: 'Human reviewed',
    icon: UserCheck,
    badgeClass: 'bg-surface-selected text-text-primary border-border',
    dotClass: 'bg-primary dark:bg-accent',
    description: 'Inspected and reviewed by a person. Human review does not automatically guarantee independent factual verification.'
  },
  [CONTENT_STATUS_FLAGS.APPROVED_FOR_EXPORT]: {
    label: 'Approved for export',
    icon: CheckCircle2,
    badgeClass: 'bg-success-subtle text-success border-success/30',
    dotClass: 'bg-success',
    description: 'Passed review and authorized for Module 6 delivery. Approval confirms review gate compliance, not absolute certainty.'
  }
};

/**
 * Reusable Content Status & Verification Flag component
 */
export default function ContentStatusBadge({
  status,
  label,
  sublabel,
  size = 'sm',
  showTooltip = true,
  className = ''
}) {
  const [isTooltipOpen, setIsTooltipOpen] = useState(false);
  const config = BADGE_CONFIG[status] || BADGE_CONFIG[CONTENT_STATUS_FLAGS.AI_GENERATED];
  const Icon = config.icon;
  const displayLabel = label || config.label;

  const sizeClasses = {
    xs: 'text-[10px] px-2 py-0.5 gap-1',
    sm: 'text-xs px-2.5 py-1 gap-1.5',
    md: 'text-xs sm:text-sm px-3 py-1.5 gap-2'
  };

  const iconSizes = {
    xs: 'w-3 h-3',
    sm: 'w-3.5 h-3.5',
    md: 'w-4 h-4'
  };

  return (
    <div className={`relative inline-flex items-center ${className}`}>
      <span
        tabIndex={0}
        role="status"
        aria-label={`${displayLabel}: ${config.description}`}
        onMouseEnter={() => showTooltip && setIsTooltipOpen(true)}
        onMouseLeave={() => showTooltip && setIsTooltipOpen(false)}
        onFocus={() => showTooltip && setIsTooltipOpen(true)}
        onBlur={() => showTooltip && setIsTooltipOpen(false)}
        className={`inline-flex items-center font-bold rounded-full border shadow-2xs transition-all cursor-help select-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus-ring ${sizeClasses[size] || sizeClasses.sm} ${config.badgeClass}`}
      >
        <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${config.dotClass}`} />
        <Icon className={`${iconSizes[size] || iconSizes.sm} shrink-0`} />
        <span>{displayLabel}</span>
        {sublabel && (
          <span className="font-normal opacity-85 pl-1 border-l border-current">
            {sublabel}
          </span>
        )}
      </span>

      {/* Accessible explainer popover using elevated surface token */}
      {isTooltipOpen && (
        <div
          role="tooltip"
          className="absolute z-50 left-0 bottom-full mb-2 w-64 p-2.5 rounded-xl bg-surface-elevated text-text-primary text-[11px] leading-relaxed shadow-xl border border-border pointer-events-none animate-fade-in"
        >
          <div className="font-bold flex items-center gap-1.5 mb-1 text-text-primary">
            <Info className="w-3.5 h-3.5 text-primary dark:text-accent" />
            <span>{config.label}</span>
          </div>
          <p className="text-text-secondary font-normal">
            {config.description}
          </p>
        </div>
      )}
    </div>
  );
}
